### PR TITLE
Add disco_config command line tool and tests.

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This PR adds the command `disco_config.py`. This command will be used to first discover the correct VLAN-specific community string for a switch. Then, using the updated community string, this command will discover the local and uplink switch ports to generate a collectd-snmp plugin configuration.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/collectd-mlab/45)

### CODE REVIEW

**Comment by nkinkade** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[disco/disco_config.py, line 128 \[r1\]](https://reviewable.io:443/reviews/m-lab/collectd-mlab/45#-KGnCrNzwRXdrIxQ4h30:-KGnCrO-tpb_xUAn_RFH:1063709677) ([raw file](https://github.com/m-lab/collectd-mlab/blob/b21a534abce3ccc3d13a20a40272323cc57f71fd/disco/disco_config.py#L128)):*
Is this docstring missing the switch_config arg?

---

*[disco/disco_config.py, line 167 \[r1\]](https://reviewable.io:443/reviews/m-lab/collectd-mlab/45#-KGnFQsL4KX17FFCPzDN:-KGnFQsMI7eHvpMRuKKu:-1296120985) ([raw file](https://github.com/m-lab/collectd-mlab/blob/b21a534abce3ccc3d13a20a40272323cc57f71fd/disco/disco_config.py#L167)):*
Is this a critical event, or really just informational?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/collectd-mlab/45)*

**Comment by stephen-soltesz** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[disco/disco_config.py, line 128 \[r1\]](https://reviewable.io:443/reviews/m-lab/collectd-mlab/45#-KGnCrNzwRXdrIxQ4h30:-KGnOn3Wr_crY0VI7z9a:1169437441) ([raw file](https://github.com/m-lab/collectd-mlab/blob/b21a534abce3ccc3d13a20a40272323cc57f71fd/disco/disco_config.py#L128)):*
Eek. Thank you for catching that. `pylint` should catch these kinds of errors, but I forgot to add this new directory to the paths that `pylint` checks in `build`.

I've fixed the docstring and added the `disco` directory to the paths checked by `pylint`.

---

*[disco/disco_config.py, line 167 \[r1\]](https://reviewable.io:443/reviews/m-lab/collectd-mlab/45#-KGnFQsL4KX17FFCPzDN:-KGnPAr5p4H30QsA-JC4:-1791879515) ([raw file](https://github.com/m-lab/collectd-mlab/blob/b21a534abce3ccc3d13a20a40272323cc57f71fd/disco/disco_config.py#L167)):*
Good question. This is critical. There are three possible states:

1. there are no vlans.
2. there are vlans, one of which contain a switch port connected to the local server.
3. there are vlans, none of which contain a switch port connected to the local server.

Cases 1 and 2 are not a problem. Case 1 corresponds to `not vlans` (an empty list). Case 2 corresponds to `vlan_found == True`.

Case 3 means that the switch has VLAN configurations (`vlans` is not empty), but we could not discover the local server's port on the switch (`vlans_found == False`). So, in this case we would not know what to monitor. And, so it's an error.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/collectd-mlab/45)*

**Comment by nkinkade** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[disco/disco_config.py, line 167 \[r1\]](https://reviewable.io:443/reviews/m-lab/collectd-mlab/45#-KGnFQsL4KX17FFCPzDN:-KGnSYOqwanfiMB_u1HO:1784115639) ([raw file](https://github.com/m-lab/collectd-mlab/blob/b21a534abce3ccc3d13a20a40272323cc57f71fd/disco/disco_config.py#L167)):*
Thanks for that explanation. I apparently wasn't reading into the conditional properly. I now see exactly why it's a critical error.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/collectd-mlab/45#-:-KGnSyN_AfBMv5OirjBP:1417088721)*

**Comment by nkinkade** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/collectd-mlab/45)*

**Pull request merged**
