### PR TITLE
Add module for loading model and OID configuration.

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This PR includes a configuration file for known switch models and a module for loading and interpreting the configuration.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/collectd-mlab/43)

### CODE REVIEW

**Comment by mtlynch** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[site-packages/mlab/disco/models.py, line 33 \[r1\]](https://reviewable.io:443/reviews/m-lab/collectd-mlab/43#-KGNcJQVuppvv9hEccOX:-KGNcJQVuppvv9hEccOY:486818290) ([raw file](https://github.com/m-lab/collectd-mlab/blob/159c9a8197809d722730b57da407d3df80f1bd1b/site-packages/mlab/disco/models.py#L33)):*
The `filename` vs. `config` semantics are a bit confusing. I'm assuming this is for unit testing? I haven't thought enough about it to suggest alternatives, but if we could eliminate the "one parameter makes the other parameter meaningless" semantics, that'd be good.

---

*[site-packages/mlab/disco/models.py, line 124 \[r1\]](https://reviewable.io:443/reviews/m-lab/collectd-mlab/43#-KGNc3QwSt3ZZ8MxDEnC:-KGNc3QwSt3ZZ8MxDEnD:1778301915) ([raw file](https://github.com/m-lab/collectd-mlab/blob/159c9a8197809d722730b57da407d3df80f1bd1b/site-packages/mlab/disco/models.py#L124)):*
It seems like if we inherit from `yaml.YAMLObject` we can do elegant parsing, if I'm understanding correctly

http://pyyaml.org/wiki/PyYAMLDocumentation#LoadingYAML

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/collectd-mlab/43)*

**Comment by stephen-soltesz** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[site-packages/mlab/disco/models.py, line 33 \[r1\]](https://reviewable.io:443/reviews/m-lab/collectd-mlab/43#-KGNcJQVuppvv9hEccOX:-KGNfTD87AOawufh5EcO:-202121321) ([raw file](https://github.com/m-lab/collectd-mlab/blob/159c9a8197809d722730b57da407d3df80f1bd1b/site-packages/mlab/disco/models.py#L33)):*
Okay. I was using the pattern from https://github.com/m-lab/collectd-mlab/pull/32 but the filename is user-provided rather than static. I think it's fine to push the file opening to the caller.

---

*[site-packages/mlab/disco/models.py, line 124 \[r1\]](https://reviewable.io:443/reviews/m-lab/collectd-mlab/43#-KGNc3QwSt3ZZ8MxDEnC:-KGNgIcoPveyO-Mg9FX9:117555596) ([raw file](https://github.com/m-lab/collectd-mlab/blob/159c9a8197809d722730b57da407d3df80f1bd1b/site-packages/mlab/disco/models.py#L124)):*
Can you say more? I'm not understanding yet. If I'm understanding correctly, the logic wouldn't change much. Perhaps `load_switch_config` could be a class method instead?

It looks like `yaml.safe_load` is preferable in `load_switch_config`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/collectd-mlab/43)*

**Comment by mtlynch** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[site-packages/mlab/disco/models.py, line 124 \[r1\]](https://reviewable.io:443/reviews/m-lab/collectd-mlab/43#-KGNc3QwSt3ZZ8MxDEnC:-KGNkioXlB0XhuPu9c3I:-1080489019) ([raw file](https://github.com/m-lab/collectd-mlab/blob/159c9a8197809d722730b57da407d3df80f1bd1b/site-packages/mlab/disco/models.py#L124)):*
Yeah, I don't have experience with PyYAML, but from a cursory look at the documentation, it seems like we can push the heavy lifting into `yaml.safe_load` instead of parsing into a dictionary and manually matching dicionary values to attributes in a `SwitchConfig` instance. It seems like if we inherit from `yaml.YAMLObject`and arrange the class attributes to match the YAML format, PyYAML will just populate the fields automatically for us, but I may be misunderstanding.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/collectd-mlab/43)*

**Comment by stephen-soltesz** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[site-packages/mlab/disco/models.py, line 124 \[r1\]](https://reviewable.io:443/reviews/m-lab/collectd-mlab/43#-KGNc3QwSt3ZZ8MxDEnC:-KGPmX_pKKG6OZeEShBm:-908844366) ([raw file](https://github.com/m-lab/collectd-mlab/blob/159c9a8197809d722730b57da407d3df80f1bd1b/site-packages/mlab/disco/models.py#L124)):*
Aah. Okay. That is possible. The file is a little longer than it was, but I hope that all parts are simpler now. It looks like the only complex logic is in `Config.__init__` for initializing the sets of model oids based on the `default_oids`.

There are a few caveats to `yaml.YAMLObject` documented in the comments for `BaseYAMLObject`. Though, I'm especially happy that we can report the line number in the exception for the offending yaml node.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/collectd-mlab/43)*

**Comment by mtlynch** [comment]
Reviewed 3 of 4 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[disco/models.yaml, line 1 \[r5\]](https://reviewable.io:443/reviews/m-lab/collectd-mlab/43#-KGS9vUZwXpED7N0VUhN:-KGS9vUZwXpED7N0VUhO:782683934) ([raw file](https://github.com/m-lab/collectd-mlab/blob/5f56c04bbfd121d1eea90c212d062e0d72b20ffe/disco/models.yaml#L1)):*
(not a deficiency in the code, just my YAML ignorance) Is my understanding correct that the `!config` etc is to define it as a `config` type in YAML so that PyYAML can translate it to a `Config` object?

---

*[disco/models.yaml, line 13 \[r5\]](https://reviewable.io:443/reviews/m-lab/collectd-mlab/43#-KGSB4maQbVCXlaAivQa:-KGSB4mb7fxzyhGWielI:-1413215355) ([raw file](https://github.com/m-lab/collectd-mlab/blob/5f56c04bbfd121d1eea90c212d062e0d72b20ffe/disco/models.yaml#L13)):*
It doesn't look like we're documenting `vlan` or `oids` (and children of `oids`)

---

*[disco/models.yaml, line 16 \[r5\]](https://reviewable.io:443/reviews/m-lab/collectd-mlab/43#-KGSApWdInucoTAesS3P:-KGSApWdInucoTAesS3Q:1104073091) ([raw file](https://github.com/m-lab/collectd-mlab/blob/5f56c04bbfd121d1eea90c212d062e0d72b20ffe/disco/models.yaml#L16)):*
Pattern seems to be property names in single quotes

---

*[disco/models.yaml, line 37 \[r5\]](https://reviewable.io:443/reviews/m-lab/collectd-mlab/43#-KGSCSmyUUmO41hFVqf8:-KGSCSmzJc8MDR_mFQ7e:-1269214095) ([raw file](https://github.com/m-lab/collectd-mlab/blob/5f56c04bbfd121d1eea90c212d062e0d72b20ffe/disco/models.yaml#L37)):*
(more YAML ignorance) Is this just a string that happens to have a curly brace in it or does `{...}` have special meaning in YAML? I've seen double curly braces for variable substitution in Ansible, but I don't know if that's an Ansible thing or a YAML thing.

Edit: After reading the rest of the code, I think the answer is that it's just a string. I'm not sure how obvious this would be to someone who's comfortable enough with YAML to recognize it as not YAML syntax. Maybe we could document that `rx` and `tx` are format strings meant to be formatted in code?

I'm still a little confused about why the format string variable is called `ifIndex` but gets populated by a parameter named `port`.

---

*[site-packages/mlab/disco/models.py, line 18 \[r5\]](https://reviewable.io:443/reviews/m-lab/collectd-mlab/43#-KGSD9yW9a5RA3023F1l:-KGSD9yW9a5RA3023F1m:-1221369250) ([raw file](https://github.com/m-lab/collectd-mlab/blob/5f56c04bbfd121d1eea90c212d062e0d72b20ffe/site-packages/mlab/disco/models.py#L18)):*
We seem to use `OID` in other comments.

---

*[site-packages/mlab/disco/models.py, line 28 \[r5\]](https://reviewable.io:443/reviews/m-lab/collectd-mlab/43#-KGSDE3V5FzKyEN1Va1x:-KGSDE3V5FzKyEN1Va1y:780712494) ([raw file](https://github.com/m-lab/collectd-mlab/blob/5f56c04bbfd121d1eea90c212d062e0d72b20ffe/site-packages/mlab/disco/models.py#L28)):*
Looks like this is missing a word or two.

---

*[site-packages/mlab/disco/models.py, line 92 \[r5\]](https://reviewable.io:443/reviews/m-lab/collectd-mlab/43#-KGSDoumBqxIZKpFGGIw:-KGSDnuGItrPHmU6obJs:1513773117) ([raw file](https://github.com/m-lab/collectd-mlab/blob/5f56c04bbfd121d1eea90c212d062e0d72b20ffe/site-packages/mlab/disco/models.py#L92)):*
Are we deliberately omitting documentation of `kwargs`?

---

*[site-packages/mlab/disco/models.py, line 93 \[r5\]](https://reviewable.io:443/reviews/m-lab/collectd-mlab/43#-KGSE_OeftroVKgtQIWv:-KGSE_OeftroVKgtQIWw:-2028902394) ([raw file](https://github.com/m-lab/collectd-mlab/blob/5f56c04bbfd121d1eea90c212d062e0d72b20ffe/site-packages/mlab/disco/models.py#L93)):*
Can we do `if not models or not default_oids`? It seems like any falsy values for these variables would be invalid. Is it legal to have a config with an empty list of models?

---

*[site-packages/mlab/disco/models.py, line 124 \[r5\]](https://reviewable.io:443/reviews/m-lab/collectd-mlab/43#-KGSFgOIxHdBbQoMV0Y6:-KGSFgOIxHdBbQoMV0Y7:-426326093) ([raw file](https://github.com/m-lab/collectd-mlab/blob/5f56c04bbfd121d1eea90c212d062e0d72b20ffe/site-packages/mlab/disco/models.py#L124)):*
If multiple patterns match, it will return the first one. Might be worth documenting or throwing an exception for.

---

*[site-packages/mlab/disco/models.py, line 167 \[r5\]](https://reviewable.io:443/reviews/m-lab/collectd-mlab/43#-KGSGMYKkU1c3WI7tN1Y:-KGSGMYKkU1c3WI7tN1Z:1200571513) ([raw file](https://github.com/m-lab/collectd-mlab/blob/5f56c04bbfd121d1eea90c212d062e0d72b20ffe/site-packages/mlab/disco/models.py#L167)):*
ditto about falsy values

---

*[site-packages/mlab/disco/models_test.py, line 11 \[r5\]](https://reviewable.io:443/reviews/m-lab/collectd-mlab/43#-KGSJLczHtYalYV0KqKD:-KGSJLczHtYalYV0KqKE:-362825670) ([raw file](https://github.com/m-lab/collectd-mlab/blob/5f56c04bbfd121d1eea90c212d062e0d72b20ffe/site-packages/mlab/disco/models_test.py#L11)):*
Very elegant unit test!

---

*[site-packages/mlab/disco/models_test.py, line 28 \[r5\]](https://reviewable.io:443/reviews/m-lab/collectd-mlab/43#-KGSHWF7iHnPNl8B0A0T:-KGSHWF7iHnPNl8B0A0U:-739120324) ([raw file](https://github.com/m-lab/collectd-mlab/blob/5f56c04bbfd121d1eea90c212d062e0d72b20ffe/site-packages/mlab/disco/models_test.py#L28)):*
I don't think we're covering the overwrite case here, and we probably want to. Suggest having a `model` with OIDs A and B and `default_oids` with OIDs B and C so we can see add (A), overwrite (B), and inherit unchanged (C).

---

*[site-packages/mlab/disco/models_test.py, line 90 \[r5\]](https://reviewable.io:443/reviews/m-lab/collectd-mlab/43#-KGSKByk_ixGp9kczsao:-KGSKByljh0O8lxFq8q1:-323180827) ([raw file](https://github.com/m-lab/collectd-mlab/blob/5f56c04bbfd121d1eea90c212d062e0d72b20ffe/site-packages/mlab/disco/models_test.py#L90)):*
Seems like weird line breaks. Is YAPF forcing this? I don't think it's worth a `# yapf: disable`, but if we can remove the early break and have YAPF accept it, suggest that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/collectd-mlab/43)*

**Comment by stephen-soltesz** [comment]
Review status: 1 of 4 files reviewed at latest revision, 13 unresolved discussions.

---

*[disco/models.yaml, line 1 \[r5\]](https://reviewable.io:443/reviews/m-lab/collectd-mlab/43#-KGS9vUZwXpED7N0VUhN:-KGSQBFrgMhpc3rhtnD4:-638359004) ([raw file](https://github.com/m-lab/collectd-mlab/blob/5f56c04bbfd121d1eea90c212d062e0d72b20ffe/disco/models.yaml#L1)):*
That's right. The convention seems to be that yaml supports "tags" http://www.yaml.org/refcard.html and PyYAML uses tags to identify the object type.

The `models.Config` class includes a class variable `yaml_tag` to know when to use the `Config` class.

---

*[disco/models.yaml, line 13 \[r5\]](https://reviewable.io:443/reviews/m-lab/collectd-mlab/43#-KGSB4maQbVCXlaAivQa:-KGSTSG9NNS8SSQ5EjSQ:-1729712789) ([raw file](https://github.com/m-lab/collectd-mlab/blob/5f56c04bbfd121d1eea90c212d062e0d72b20ffe/disco/models.yaml#L13)):*
I've added more notes here and deferred the documentation for `oids` and `oid` to the `default_oids` section below.

How does it look?

---

*[disco/models.yaml, line 16 \[r5\]](https://reviewable.io:443/reviews/m-lab/collectd-mlab/43#-KGSApWdInucoTAesS3P:-KGSTbQL5krd5gp634Hl:1869566405) ([raw file](https://github.com/m-lab/collectd-mlab/blob/5f56c04bbfd121d1eea90c212d062e0d72b20ffe/disco/models.yaml#L16)):*
Yes. Fixed throughout.

---

*[disco/models.yaml, line 37 \[r5\]](https://reviewable.io:443/reviews/m-lab/collectd-mlab/43#-KGSCSmyUUmO41hFVqf8:-KGSUN5diONDWlltotq9:-1676966730) ([raw file](https://github.com/m-lab/collectd-mlab/blob/5f56c04bbfd121d1eea90c212d062e0d72b20ffe/disco/models.yaml#L37)):*
I've added more clarifying text that the OIDs are "format strings". That is helpful to clarify.

"ifIndex" is an SNMP thing that basically means port... most of the time. I changed the parameter to lookup_oids to use `ifindex` instead of `port` for consistency.

I was trying to be helpful to humans who may understand what a switch port is but not be sure of what an ifindex is. But, this may be another example where some domain familiarity is necessary and using ifIndex throughout is actually more helpful by hinting that "you need to know what an ifindex is."

---

*[site-packages/mlab/disco/models.py, line 18 \[r5\]](https://reviewable.io:443/reviews/m-lab/collectd-mlab/43#-KGSD9yW9a5RA3023F1l:-KGSUocQgbmU6mAcW8x9:-843463799) ([raw file](https://github.com/m-lab/collectd-mlab/blob/5f56c04bbfd121d1eea90c212d062e0d72b20ffe/site-packages/mlab/disco/models.py#L18)):*
Fixed. I've also updated the use of `Oid` in class and function names to `OID` for consistency.

---

*[site-packages/mlab/disco/models.py, line 28 \[r5\]](https://reviewable.io:443/reviews/m-lab/collectd-mlab/43#-KGSDE3V5FzKyEN1Va1x:-KGSV-pO08FHBQjZrsVF:1743833013) ([raw file](https://github.com/m-lab/collectd-mlab/blob/5f56c04bbfd121d1eea90c212d062e0d72b20ffe/site-packages/mlab/disco/models.py#L28)):*
lol. `NotInitialized` is not used. Removed.

---

*[site-packages/mlab/disco/models.py, line 92 \[r5\]](https://reviewable.io:443/reviews/m-lab/collectd-mlab/43#-KGSDoumBqxIZKpFGGIw:-KGSVstKaZWBUiYccodu:-479311318) ([raw file](https://github.com/m-lab/collectd-mlab/blob/5f56c04bbfd121d1eea90c212d062e0d72b20ffe/site-packages/mlab/disco/models.py#L92)):*
Not deliberately. Fixed. Evidently none of our pre-checks flag this.

---

*[site-packages/mlab/disco/models.py, line 93 \[r5\]](https://reviewable.io:443/reviews/m-lab/collectd-mlab/43#-KGSE_OeftroVKgtQIWv:-KGSWHnM7NS1Tfn1Bt2g:1190922827) ([raw file](https://github.com/m-lab/collectd-mlab/blob/5f56c04bbfd121d1eea90c212d062e0d72b20ffe/site-packages/mlab/disco/models.py#L93)):*
Okay. I tend to favor being specific. But, a config with an empty list of models would not be so helpful, you're right. I still want to preserve and empty default_oids for testing, since a model could declare all of it's oids.

---

*[site-packages/mlab/disco/models.py, line 124 \[r5\]](https://reviewable.io:443/reviews/m-lab/collectd-mlab/43#-KGSFgOIxHdBbQoMV0Y6:-KGSYARMoYm6SdbuC_Fp:-1891417126) ([raw file](https://github.com/m-lab/collectd-mlab/blob/5f56c04bbfd121d1eea90c212d062e0d72b20ffe/site-packages/mlab/disco/models.py#L124)):*
That's a good idea. Multiple matches is a problem with configuration that deserves to be flagged. Added.

---

*[site-packages/mlab/disco/models.py, line 167 \[r5\]](https://reviewable.io:443/reviews/m-lab/collectd-mlab/43#-KGSGMYKkU1c3WI7tN1Y:-KGSZUJxcLBefYyo7KcM:-499146009) ([raw file](https://github.com/m-lab/collectd-mlab/blob/5f56c04bbfd121d1eea90c212d062e0d72b20ffe/site-packages/mlab/disco/models.py#L167)):*
Done.

---

*[site-packages/mlab/disco/models_test.py, line 11 \[r5\]](https://reviewable.io:443/reviews/m-lab/collectd-mlab/43#-KGSJLczHtYalYV0KqKD:-KGSaXXnv3gQ2Bl68wL4:321007250) ([raw file](https://github.com/m-lab/collectd-mlab/blob/5f56c04bbfd121d1eea90c212d062e0d72b20ffe/site-packages/mlab/disco/models_test.py#L11)):*
Thank you! I love it when we don't need mocks.

---

*[site-packages/mlab/disco/models_test.py, line 28 \[r5\]](https://reviewable.io:443/reviews/m-lab/collectd-mlab/43#-KGSHWF7iHnPNl8B0A0T:-KGSaUyu4ZkUE_jDqqP5:-513105973) ([raw file](https://github.com/m-lab/collectd-mlab/blob/5f56c04bbfd121d1eea90c212d062e0d72b20ffe/site-packages/mlab/disco/models_test.py#L28)):*
Oh, great point. Added.

---

*[site-packages/mlab/disco/models_test.py, line 90 \[r5\]](https://reviewable.io:443/reviews/m-lab/collectd-mlab/43#-KGSKByk_ixGp9kczsao:-KGSa_s4UouAdtD8tUvu:744929398) ([raw file](https://github.com/m-lab/collectd-mlab/blob/5f56c04bbfd121d1eea90c212d062e0d72b20ffe/site-packages/mlab/disco/models_test.py#L90)):*
Yeah, this is yapf. I thought it was weird too. I tried initializing the dict differently to prevent this. Unfortunate to work around the auto-formatter, but better than the weird formatting too I think.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/collectd-mlab/43)*

**Comment by mtlynch** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[disco/models.yaml, line 60 \[r6\]](https://reviewable.io:443/reviews/m-lab/collectd-mlab/43#-KGT-nRTHuVo3UF0YVhW:-KGT-nRTHuVo3UF0YVhX:-1052877027) ([raw file](https://github.com/m-lab/collectd-mlab/blob/abd9c1120048f031851b6ed3fcd3aa2add3c462c/disco/models.yaml#L60)):*
formats -> format

---

*[disco/models.yaml, line 62 \[r6\]](https://reviewable.io:443/reviews/m-lab/collectd-mlab/43#-KGT-gr-OmvCw4-hmN3W:-KGT-gr1domaTyFNx_JP:786158637) ([raw file](https://github.com/m-lab/collectd-mlab/blob/abd9c1120048f031851b6ed3fcd3aa2add3c462c/disco/models.yaml#L62)):*
Suggest a comma after "values"

---

*[site-packages/mlab/disco/models.py, line 142 \[r6\]](https://reviewable.io:443/reviews/m-lab/collectd-mlab/43#-KGT06PaBfI6vj4audfo:-KGT06PbVdPrFgm9_8mB:1471802553) ([raw file](https://github.com/m-lab/collectd-mlab/blob/abd9c1120048f031851b6ed3fcd3aa2add3c462c/site-packages/mlab/disco/models.py#L142)):*
Might be useful to include the matching model patterns in the error message as well.

---

*[site-packages/mlab/disco/models_test.py, line 90 \[r5\]](https://reviewable.io:443/reviews/m-lab/collectd-mlab/43#-KGSKByk_ixGp9kczsao:-KGT0mTlssXxGb60DKQ9:1727638239) ([raw file](https://github.com/m-lab/collectd-mlab/blob/5f56c04bbfd121d1eea90c212d062e0d72b20ffe/site-packages/mlab/disco/models_test.py#L90)):*
Might be worth filing:

https://github.com/google/yapf/issues

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/collectd-mlab/43#-:-KGT0r4WvSqi-gWCQqJT:1417088721)*

**Comment by stephen-soltesz** [comment]
Review status: 2 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[disco/models.yaml, line 60 \[r6\]](https://reviewable.io:443/reviews/m-lab/collectd-mlab/43#-KGT-nRTHuVo3UF0YVhW:-KGTH58w2T_hDE0ioIpQ:-499146009) ([raw file](https://github.com/m-lab/collectd-mlab/blob/abd9c1120048f031851b6ed3fcd3aa2add3c462c/disco/models.yaml#L60)):*
Done.

---

*[disco/models.yaml, line 62 \[r6\]](https://reviewable.io:443/reviews/m-lab/collectd-mlab/43#-KGT-gr-OmvCw4-hmN3W:-KGTH9TyDCzYV_VYndQC:-499146009) ([raw file](https://github.com/m-lab/collectd-mlab/blob/abd9c1120048f031851b6ed3fcd3aa2add3c462c/disco/models.yaml#L62)):*
Done.

---

*[site-packages/mlab/disco/models.py, line 142 \[r6\]](https://reviewable.io:443/reviews/m-lab/collectd-mlab/43#-KGT06PaBfI6vj4audfo:-KGTHW-MzecaL_AkFGoW:-2128067485) ([raw file](https://github.com/m-lab/collectd-mlab/blob/abd9c1120048f031851b6ed3fcd3aa2add3c462c/site-packages/mlab/disco/models.py#L142)):*
I wondered about this. Sounds like we have consensus. Done.

---

*[site-packages/mlab/disco/models_test.py, line 90 \[r5\]](https://reviewable.io:443/reviews/m-lab/collectd-mlab/43#-KGSKByk_ixGp9kczsao:-KGTIg9dXwBQWsX4H9Zt:-1265750276) ([raw file](https://github.com/m-lab/collectd-mlab/blob/5f56c04bbfd121d1eea90c212d062e0d72b20ffe/site-packages/mlab/disco/models_test.py#L90)):*
Done.

https://github.com/google/yapf/issues/245

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/collectd-mlab/43)*

**Pull request merged**
