### PR TITLE
Fixes for yapf, pyflakes and pylint.

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This PR fixes lint warnings produced by pyflakes and pylint.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/collectd-mlab/30)

### CODE REVIEW

**Comment by mtlynch** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[.travis.yml, line 13 \[r1\]](https://reviewable.io:443/reviews/m-lab/collectd-mlab/30#-KFK5BRL4o7KsvTyc26k:-KFK5BRL4o7KsvTyc26l:239951812) ([raw file](https://github.com/m-lab/collectd-mlab/blob/04e4267129555cf924b97f751f016ca3ac47d728/.travis.yml#L13)):*
I'm still kind of undecided about explicit versioning. For things that can break us when they improve (like YAPF, pyflakes, pylint), I always choose explicit versions. But for things where improvements are unlikely to break us, I feel like we might as well always take latest-and-greatest.

---

*[.travis.yml, line 16 \[r1\]](https://reviewable.io:443/reviews/m-lab/collectd-mlab/30#-KFK5TgG3mP5fN-bOsJv:-KFK5TgG3mP5fN-bOsJw:1528251467) ([raw file](https://github.com/m-lab/collectd-mlab/blob/04e4267129555cf924b97f751f016ca3ac47d728/.travis.yml#L16)):*
It looks like we're making these fixes with pylint + DocStringChecker, but they're not part of the build script. Can we add them to the build so this correctness gets locked in? Example implementation:

https://github.com/m-lab/ndt-e2e-clientworker/pull/12

---

*[plugin/mlab_test.py, line 344 \[r1\]](https://reviewable.io:443/reviews/m-lab/collectd-mlab/30#-KFK4zRYMFv2qJTX0TN2:-KFK4zRYMFv2qJTX0TN3:-325230171) ([raw file](https://github.com/m-lab/collectd-mlab/blob/04e4267129555cf924b97f751f016ca3ac47d728/plugin/mlab_test.py#L344)):*
The unused prefix seems right here. Does DocStringChecker complain about it? Will `_` work?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/collectd-mlab/30)*

**Comment by stephen-soltesz** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[.travis.yml, line 13 \[r1\]](https://reviewable.io:443/reviews/m-lab/collectd-mlab/30#-KFK5BRL4o7KsvTyc26k:-KFKLHzTb5i8IWrxuN0n:1037170107) ([raw file](https://github.com/m-lab/collectd-mlab/blob/04e4267129555cf924b97f751f016ca3ac47d728/.travis.yml#L13)):*
I don't have a strong feeling here. This is the form in https://github.com/m-lab/ndt-e2e-clientworker/blob/master/.travis.yml that I copied uncritically.

---

*[.travis.yml, line 16 \[r1\]](https://reviewable.io:443/reviews/m-lab/collectd-mlab/30#-KFK5TgG3mP5fN-bOsJv:-KFKLhZNcaRTl5WuwTf9:-1350432254) ([raw file](https://github.com/m-lab/collectd-mlab/blob/04e4267129555cf924b97f751f016ca3ac47d728/.travis.yml#L16)):*
No problem. I wasn't sure if copying the lint plugin multiple times was the right way to go and didn't want to include too much in a "whitespace" PR. But, now it sounds like it should be in this PR, so now it is.

---

*[plugin/mlab_test.py, line 344 \[r1\]](https://reviewable.io:443/reviews/m-lab/collectd-mlab/30#-KFK4zRYMFv2qJTX0TN2:-KFKQEpDIXxpUnxodTuk:-1939402266) ([raw file](https://github.com/m-lab/collectd-mlab/blob/04e4267129555cf924b97f751f016ca3ac47d728/plugin/mlab_test.py#L344)):*
This code was due to a work around for the python-2.6 version of mock (only on CentOS 6). Since we had trouble getting that working in travis, the tests are run with python-2.7 anyway. So, I've removed this code entirely in favor of the simpler form of `.side_effect`.

The original lint error was below. I think the "*" was throwing it off:
"C:344, 8: Variable args/keywords are named *args/**kwargs, not unused_args (docstring-misnamed-args)"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/collectd-mlab/30)*

**Comment by mtlynch** [comment]
:lgtm:

---

Review status: 0 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[.travis.yml, line 13 \[r1\]](https://reviewable.io:443/reviews/m-lab/collectd-mlab/30#-KFK5BRL4o7KsvTyc26k:-KFKWlXk2fl9uUNzp4X8:-30838227) ([raw file](https://github.com/m-lab/collectd-mlab/blob/04e4267129555cf924b97f751f016ca3ac47d728/.travis.yml#L13)):*
Yeah the contractor wrote that and I just let it go, but for this I'd say if you have no strong feelings, I vote unversioned.

---

*[plugin/mlab_test.py, line 344 \[r1\]](https://reviewable.io:443/reviews/m-lab/collectd-mlab/30#-KFK4zRYMFv2qJTX0TN2:-KFKX76sJsm3Ap3LhsYG:-1105181439) ([raw file](https://github.com/m-lab/collectd-mlab/blob/04e4267129555cf924b97f751f016ca3ac47d728/plugin/mlab_test.py#L344)):*
Removed? It looks like it's still here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/collectd-mlab/30#-:-KFKXJi5PSKNROrbshoN:1417088721)*

**Comment by stephen-soltesz** [comment]
Review status: 0 of 10 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[.travis.yml, line 13 \[r1\]](https://reviewable.io:443/reviews/m-lab/collectd-mlab/30#-KFK5BRL4o7KsvTyc26k:-KFKgrZspxpXa-Si_9Nb:-499146009) ([raw file](https://github.com/m-lab/collectd-mlab/blob/04e4267129555cf924b97f751f016ca3ac47d728/.travis.yml#L13)):*
Done.

---

*[plugin/mlab_test.py, line 344 \[r1\]](https://reviewable.io:443/reviews/m-lab/collectd-mlab/30#-KFK4zRYMFv2qJTX0TN2:-KFKgt4z2tMXl4YSOSoz:399274562) ([raw file](https://github.com/m-lab/collectd-mlab/blob/04e4267129555cf924b97f751f016ca3ac47d728/plugin/mlab_test.py#L344)):*
Derp. Forgot to push. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/collectd-mlab/30)*

**Pull request merged**
